GBTAmmoniaSurvey/GAS

- mapping/GAS_pipeline_wrapper.py
- scripts/autopeak_Jupiter
- scripts/autopeak_L1489PPC
- scripts/autopeak_oriona
- scripts/autopeak_perseus
- scripts/nodJupiter
- scripts/oriona_map_10arcmin_square
- scripts/peak_3C48
- scripts/track_L1489PPC
> First look mapping pipeline

- ds9_region_files/observing_scripts/vegas_kfpa_config
-Adds VEGAS configuration for total power (position switching) observations. JEP
> Add total power configuration

- mapping/CasaRegrid.py
- mapping/PropertyMaps.py
- mapping/otf_gbtmap_grid.pro
I've adapted the `pyspeckit` property mapping code to work with the NGC1333 data.  There are still some issues.  Code requires `spectral_cube`
> Property mapping code

- mapping/gasPipeline.py
Pipeline improvements including
*   Region based pipeline generation; processes all maps associated with `Region Name` into a single directory.
*   Directories now named based on species i.e., `NGC1333_NH3_11`
*   Automatically downloads and updates logs from Google if file is not available.
*   Added session number to scans to prevent name clashes.
*   Removed code associated with gridding through AIPS since we don't use it.
This change to the pipeline bundles the data into window based directories for an entire region based on the `Region Name` tag in the spreadsheet.
> Directory based pipeline

- mapping/gasPipeline.py
The pipeline now checks to see if the files that will be produced are already on disk in the target area.  If they are, this does not re-reduce them.  If you want to trigger a re-reduction, they can be deleted from disk or the `overwrite=True` keyword can be set. Default is naturally `False`
> Adding restart and amendment functionality

- mapping/gasPipeline.py
- mapping/gridregion.py
First cut at gridding that seems to be okay.  This still needs some debugging but I'm pushing upstream now so @jpinedaf can get a chance to identify problems.   Example call:
```
execfile('/users/erosolow/GAS/mapping/gridregion.py')
griddata(dirname = 'NGC1333_C2S',startChannel=1848,endChannel=2248)
```
Next up, debug missing pixels, work out proper weights from inverse variance, check gridding kernels and move beyond `jinc` and package pipelines into a module.
> Grid pipeline

- mapping/gasPipeline.py
- mapping/gridregion.py
*   Headers more robust; parseable in CASA
*   Correctly in VRAD-LSR... I think
*   Gridding reset to correct.
*   Fractional channel shifting in place.
*   Initial baselining attempt.
> Baselines and frequency shifts.

- GAS/run_first_look.py
> Rename CCS FITS file

- GAS/run_grid_regions.py
Hi Jaime and Rachel,
I have identified the range of emission channels and modified the L1455 section in run_grid_regions.py.  Please review it.  For the lines that I don't see emissions I select the channels the same as in NH3_22.  For HC7N_21_20 I noticed that the emission channels are very close the edge of the band, and I see absorption features that are possibly from frequency switching (but I don't see this in other lines than NH3_11).  
Please let me know if you have any questions. 
Cheers,
Katherine
> L1455 Modified

- GAS/run_first_look.py
Hi Jaime,
I have added a section for L1455 in run_first_look.py.  Please review it and accepted it.  Let me know if you would like me to run the first look script.  
Thanks,
Katherine
> L1455 added

- GAS/run_first_look.py
-Channel selection for NH3 (1,1) in B18
> Initial work for First Look pipeline in B18

- GAS/run_first_look.py
-Previous commit had mixed channel ranges
> Fixed B18 channel range

- GAS/run_grid_regions.py
> update starChannel/endChannel for L1688

- GAS/run_first_look.py
> Update a_rms/b_rms/index_peak for L1688

- GAS/first_look.py
- GAS/run_first_look.py
Instead of the moment1, the `vpeak` maps give another view of where the emission is found.  Note there is an offset between vpeak and mom1 values because the central hyperfine is asymmetric.
> Velocity of peak of the emission + NGC 1333 better channel selections

- GAS/run_first_look.py
No significant emission in both HC7N transitions. They are skipped for the moment.
> Update for L1688

- GAS/run_first_look.py
> Update for NH3 (3, 3) for L1688

- GAS/run_first_look.py
> minor edit

- GAS/PropertyMaps.py
- GAS/__init__.py
- GAS/first_look.py
- GAS/gasPipeline.py
- GAS/run_first_look.py
Also merge conflicts with @hopehhchen
> Some tweaks to parameter mapping.  

- GAS/PropertyMaps.py
Initial efforts to display fitting results, but including some masking to account for QA.
Minor updates to the fitting function, change of deprecated .units -> .unit in pyspeckit
> Property map

- GAS/PropertyMaps.py
-Useful to store the parameters of the fit that we like
> Add function to run and plot fits for regions

- GAS/PropertyMaps.py
-new function to convert storage of fitted parameters between data
cube and hdu file
-TODO modify plotting function and fitting function to use hdu
> Conversion function for fit parameter file

- GAS/PropertyMaps.py
-Update documentation of functions in PropertyMaps.py
-Updated parameters for fit and plotting of NGC1333
> Update documentation and storage of legacy results

- GAS/gasPipeline.py
- GAS/run_first_look.py
-Extra whitespaces in gasPipeline for clearer view
-Update on Serpens_Aquila first look function to use
proper folder instead of *_test
> Update on pipeline

- GAS/gasPipeline.py
This seems like a more sensible default.
> Be inclusive

- GAS/run_first_look.py
- GAS/run_grid_regions.py
prepare gridding and first look functions to be DR1 compatible
> continue preparation of DR1... work in progress DO NOT MERGE yet

- GAS/run_grid_regions.py
> Initial TMC1 gridding function

- GAS/run_first_look.py
- GAS/run_grid_regions.py
- releases/DR1.py
creates gridding function and first look function. It also updates DR1.py to include these new functions
> Splits OrionB into two subregions: NGC2023/2024 and NGC2068/2071

- GAS/run_first_look.py
-Initial creation of L1689 first look function
-So far this region does not include any detection, need more
obervations or new gridding to check this
> Add L1689 First Look

- docs/calibration.rst
- docs/first_look.rst
- docs/imaging.rst
- docs/index.rst
- docs/property_map.rst
first attempt... trying to get something running
> more information into the docs. Mostly based on the GAS cheatsheet

- GAS/first_look.py
- GAS/gasPipeline.py
- GAS/run_first_look.py
This pulls out and generalizes first look info to reflect the content in the observing logs.
> Create FirstLook() functionality

- GAS/gasBinning.py
This address #92 by making `CentroidMap` a parameter.
> Make the default for stacking be no velocity shift

- GAS/PropertyMaps.py
As discussed on telecon.  Further edits probably needed.
> NH3 fitting: ortho fraction fixed to zero

- GAS/run_grid_regions.py
[] Converted Cepheus gridding function into Cepheus_L1228
[] Added gridder for Cepheus_L1251
> Grid functions: Cepheus L1228 and L1251

- GAS/run_first_look.py
Created initial commit for Cepheus (L1228 and L1251) first look
> Cepheus First Look

- GAS/run_first_look.py
- GAS/run_grid_regions.py
combine the TCM1 and HC2 region
> Merge TMC1 into HC2

- GAS/gasPipeline.py
-Add function to move files if left behind by pipeline
-related to issue #55
> No files left behind

- ds9_region_files/Serpens_GAS_box.reg
Add DS9 region file showing footprints for Serpens_Aquila
> Serpens footprints: DS9 region file

- GAS/run_grid_regions.py
update to B59 griding function
> B59 cube making update

- GAS/PropertyMaps.py
- docs/first_look.rst
- docs/property_map.rst
- Updated call to cubefit and plot_cubefit to include the file_extension keywords
> Update line fitting and first look documentation

- GAS/PropertyMaps.py
I corrected file names in flag_all_data method.
> File change in flag_all_data

- GAS/PropertyMaps.py
I update both cubefit and update_NH3_momento0 with the new cold_ammonia model from pyspeckit. 
I tested it on B59, and it should work!
> Update cold_ammonia model

- GAS/PropertyMaps.py
- GAS/__init__.py
- GAS/baseline.py
- GAS/gasPipeline.py
- GAS/gridregion.py
- GAS/run_first_look.py
- GAS/run_grid_regions.py
- GAS/utils.py
All right.  After much ado (and slow response-loop), I've made some improvements to the rebaselining code.  The major improvement is the creation of `run_rebaseline.py` and the ability to do it after the gridding. I also found an error that was corrupting the estimates of the velocity centre in OrionA which made that region better. Plus lots of little bugs that are now better.  I'll send an email about my view on the next analysis steps and the outcomes.
> Bugfixes and improvements to Baselines

- GAS/baseline.py
- GAS/first_look.py
add back capability of removing edges which was lost with the improved re-baselining. This is related to 
https://github.com/GBTAmmoniaSurvey/DR1_analysis/issues/1
@rfriesen @low-sky
> Remove edge

- GAS/PropertyMaps.py
Flagging based on S/N in NH3 (1,1) and uncertainties in Tex, Tk results.
> Updates to flagging property maps for DR1 release, plotting

- GAS/gasPipeline.py
As per #152 , update to `gbtpipeline` as the main call.  While I was in there, my text editor got angry at the non-PEP8 formatting so there are a ton of cosmetic issues too.
> Change to gbtpipeline for running pipeline.

- GAS/PropertyMaps.py
Fixes (so far) masked pixels in rms maps noted in #171 
Probably doesn't catch all fit failures. 
Also improves 'speckly' appearance of some moment maps.
> Added additional checks for bad fits in update_NH3_moment0

- GAS/plot_regions.py
Requires config.py file that includes distances for scalebars.
> Adding NH3 property map plots
